homepage:
    pattern:  /
    defaults: { _controller: AcerosRegisterBundle:Default:index }
html:
    pattern:  /html
    defaults: { _controller: AcerosRegisterBundle:Default:html }
inscripciones:
    pattern:  /inscripciones
    defaults: { _controller: AcerosRegisterBundle:Inscripciones:index }